### ISSUE TITLE
Can't use ores--Simply Solar Cables no longer attach. 

### ISSUE THREAD

**Issue by theloraxe** [IHOC/Server#12] opened 2017-03-14 16:53 UTC
When submitting a bug report, to save us and yourself time, and to ensure we actually have the needed information to take care 
of your issue, please make sure you submit the following information (failure to provide all listed information may result in 
your bug not being addressed):

http://gist.github.com is the prefered site for all reports, logs, and lists.

TeamIHOC Server issue occurred on (Identified by modpack installed ie. All The Mods): Sky Factory 3

Narrative description of issue or crash: Hello--and Thanks for helping--The sifted ores--copper, gold and the like, when put into a crafting station will not process into the broken ores for smelting. Nothing appears in the output box when you put any of the ores into a crafting station in a 2X2 matrix. Also since about four or five days ago, the simply solar cables will no longer connect to items like the heavy crusher or compressor. 

Steps to reproduce the issue or crash: None--it is constant and has been this way for about five days now--I keep thinking it will be fixed with the next update but it is not.

Link to crash report (posted on either http://gist.github.com or http://www.pastebin.com): Does not crash 

Link to console logs (posted on http://gist.github.com):

OS of Client computer: Windows 10--

Version of JAVA on Client: 8

Version of Minecraft: Latest

Version of Forge:

List of ALL mods installed (posted to either http://www.pastebin.com or http://gist.github.com):

**Comment by Gunner76th** [comment] 2017-03-14 17:51
As to the solar cables, this is a known issue. We are not sure as to why it is happening. We are working to submit a bug report to the mod dev.

As to the ores not crafting, We cannot reproduce this problem on our server. Please provide screen shots of how you are attempting to craft them. Please note, that the crushed ore no longer crafts into broken ore, but instead into actual ore blocks.

**Comment by SoulK1ller** [comment] 2019-11-05 01:56
Closing this issue.

**Closed as completed** 2019-11-07 01:58 UTC
